//! Raw FFI bindings to the Kvaser CANLib SDK.
//!
//! This crate provides unsafe, low-level bindings generated by bindgen.
//! For a safe, idiomatic Rust API, use the `canlib` crate instead.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Re-export commonly used types for convenience
pub type canHandle = ::std::os::raw::c_int;
pub type canStatus = ::std::os::raw::c_int;

// ---- Status codes ----

pub const canOK: canStatus = 0;
pub const canERR_PARAM: canStatus = -1;
pub const canERR_NOMSG: canStatus = -2;
pub const canERR_NOTFOUND: canStatus = -3;
pub const canERR_NOMEM: canStatus = -4;
pub const canERR_NOCHANNELS: canStatus = -5;
pub const canERR_INTERRUPTED: canStatus = -6;
pub const canERR_TIMEOUT: canStatus = -7;
pub const canERR_NOTINITIALIZED: canStatus = -8;
pub const canERR_NOHANDLES: canStatus = -9;
pub const canERR_INVHANDLE: canStatus = -10;
pub const canERR_INIFILE: canStatus = -11;
pub const canERR_DRIVER: canStatus = -12;
pub const canERR_TXBUFOFL: canStatus = -13;
pub const canERR_RESERVED_1: canStatus = -14;
pub const canERR_HARDWARE: canStatus = -15;
pub const canERR_DYNALOAD: canStatus = -16;
pub const canERR_DYNALIB: canStatus = -17;
pub const canERR_DYNAINIT: canStatus = -18;
pub const canERR_NOT_SUPPORTED: canStatus = -19;
pub const canERR_RESERVED_5: canStatus = -20;
pub const canERR_RESERVED_6: canStatus = -21;
pub const canERR_RESERVED_2: canStatus = -22;
pub const canERR_DRIVERLOAD: canStatus = -23;
pub const canERR_DRIVERFAILED: canStatus = -24;
pub const canERR_NOCONFIGMGR: canStatus = -25;
pub const canERR_NOCARD: canStatus = -26;
pub const canERR_RESERVED_7: canStatus = -27;
pub const canERR_REGISTRY: canStatus = -28;
pub const canERR_LICENSE: canStatus = -29;
pub const canERR_INTERNAL: canStatus = -30;
pub const canERR_NO_ACCESS: canStatus = -31;
pub const canERR_NOT_IMPLEMENTED: canStatus = -32;
pub const canERR_DEVICE_FILE: canStatus = -33;
pub const canERR_HOST_FILE: canStatus = -34;
pub const canERR_DISK: canStatus = -35;
pub const canERR_CRC: canStatus = -36;
pub const canERR_CONFIG: canStatus = -37;
pub const canERR_MEMO_FAIL: canStatus = -38;
pub const canERR_SCRIPT_FAIL: canStatus = -39;
pub const canERR_SCRIPT_WRONG_VERSION: canStatus = -40;

// ---- Open channel flags ----

pub const canOPEN_EXCLUSIVE: ::std::os::raw::c_int = 0x0008;
pub const canOPEN_REQUIRE_EXTENDED: ::std::os::raw::c_int = 0x0010;
pub const canOPEN_ACCEPT_VIRTUAL: ::std::os::raw::c_int = 0x0020;
pub const canOPEN_OVERRIDE_EXCLUSIVE: ::std::os::raw::c_int = 0x0040;
pub const canOPEN_REQUIRE_INIT_ACCESS: ::std::os::raw::c_int = 0x0080;
pub const canOPEN_NO_INIT_ACCESS: ::std::os::raw::c_int = 0x0100;
pub const canOPEN_ACCEPT_LARGE_DLC: ::std::os::raw::c_int = 0x0200;
pub const canOPEN_CAN_FD: ::std::os::raw::c_int = 0x0400;
pub const canOPEN_CAN_FD_NONISO: ::std::os::raw::c_int = 0x0800;

// ---- Predefined bitrates ----

pub const canBITRATE_1M: ::std::os::raw::c_long = -1;
pub const canBITRATE_500K: ::std::os::raw::c_long = -2;
pub const canBITRATE_250K: ::std::os::raw::c_long = -3;
pub const canBITRATE_125K: ::std::os::raw::c_long = -4;
pub const canBITRATE_100K: ::std::os::raw::c_long = -5;
pub const canBITRATE_62K: ::std::os::raw::c_long = -6;
pub const canBITRATE_50K: ::std::os::raw::c_long = -7;
pub const canBITRATE_83K: ::std::os::raw::c_long = -8;
pub const canBITRATE_10K: ::std::os::raw::c_long = -9;

pub const canFD_BITRATE_500K_80P: ::std::os::raw::c_long = -1000;
pub const canFD_BITRATE_1M_80P: ::std::os::raw::c_long = -1001;
pub const canFD_BITRATE_2M_80P: ::std::os::raw::c_long = -1002;
pub const canFD_BITRATE_4M_80P: ::std::os::raw::c_long = -1003;
pub const canFD_BITRATE_8M_60P: ::std::os::raw::c_long = -1004;
pub const canFD_BITRATE_8M_80P: ::std::os::raw::c_long = -1005;
pub const canFD_BITRATE_8M_70P: ::std::os::raw::c_long = -1006;

// ---- Message flags ----

pub const canMSG_RTR: ::std::os::raw::c_uint = 0x0001;
pub const canMSG_STD: ::std::os::raw::c_uint = 0x0002;
pub const canMSG_EXT: ::std::os::raw::c_uint = 0x0004;
pub const canMSG_WAKEUP: ::std::os::raw::c_uint = 0x0008;
pub const canMSG_NERR: ::std::os::raw::c_uint = 0x0010;
pub const canMSG_ERROR_FRAME: ::std::os::raw::c_uint = 0x0020;
pub const canMSG_TXACK: ::std::os::raw::c_uint = 0x0040;
pub const canMSG_TXRQ: ::std::os::raw::c_uint = 0x0080;
pub const canMSG_DELAY_MSG: ::std::os::raw::c_uint = 0x0100;

pub const canFDMSG_FDF: ::std::os::raw::c_uint = 0x010000;
pub const canFDMSG_BRS: ::std::os::raw::c_uint = 0x020000;
pub const canFDMSG_ESI: ::std::os::raw::c_uint = 0x040000;

// ---- Driver types ----

pub const canDRIVER_NORMAL: ::std::os::raw::c_uint = 4;
pub const canDRIVER_SILENT: ::std::os::raw::c_uint = 1;
pub const canDRIVER_SELFRECEPTION: ::std::os::raw::c_uint = 8;
pub const canDRIVER_OFF: ::std::os::raw::c_uint = 0;

// ---- Filter flags ----

pub const canFILTER_ACCEPT: ::std::os::raw::c_uint = 1;
pub const canFILTER_REJECT: ::std::os::raw::c_uint = 2;
pub const canFILTER_SET_CODE_STD: ::std::os::raw::c_uint = 3;
pub const canFILTER_SET_MASK_STD: ::std::os::raw::c_uint = 4;
pub const canFILTER_SET_CODE_EXT: ::std::os::raw::c_uint = 5;
pub const canFILTER_SET_MASK_EXT: ::std::os::raw::c_uint = 6;

// ---- Channel data items ----

pub const canCHANNELDATA_CARD_SERIAL_NO: ::std::os::raw::c_int = 7;
pub const canCHANNELDATA_CARD_UPC_NO: ::std::os::raw::c_int = 8;
pub const canCHANNELDATA_CARD_FIRMWARE_REV: ::std::os::raw::c_int = 9;
pub const canCHANNELDATA_CARD_HARDWARE_REV: ::std::os::raw::c_int = 10;
pub const canCHANNELDATA_CHANNEL_CAP: ::std::os::raw::c_int = 1;
pub const canCHANNELDATA_DEVDESCR_ASCII: ::std::os::raw::c_int = 26;
pub const canCHANNELDATA_CHANNEL_NAME: ::std::os::raw::c_int = 13;

// ---- Bus status flags ----

pub const canSTAT_ERROR_PASSIVE: ::std::os::raw::c_ulong = 0x00000001;
pub const canSTAT_BUS_OFF: ::std::os::raw::c_ulong = 0x00000002;
pub const canSTAT_ERROR_WARNING: ::std::os::raw::c_ulong = 0x00000004;
pub const canSTAT_ERROR_ACTIVE: ::std::os::raw::c_ulong = 0x00000008;
pub const canSTAT_TX_PENDING: ::std::os::raw::c_ulong = 0x00000010;
pub const canSTAT_RX_PENDING: ::std::os::raw::c_ulong = 0x00000020;
pub const canSTAT_OVERRUN: ::std::os::raw::c_ulong = 0x00000080;

// ---- Structs ----

#[repr(C)]
#[derive(Debug, Default, Clone, Copy)]
pub struct kvBusParamsTq {
    pub tq: ::std::os::raw::c_int,
    pub phase1: ::std::os::raw::c_int,
    pub phase2: ::std::os::raw::c_int,
    pub sjw: ::std::os::raw::c_int,
    pub prop: ::std::os::raw::c_int,
    pub prescaler: ::std::os::raw::c_int,
}

#[repr(C)]
#[derive(Debug, Default, Clone, Copy)]
pub struct canBusStatistics {
    pub stdData: ::std::os::raw::c_ulong,
    pub stdRemote: ::std::os::raw::c_ulong,
    pub extData: ::std::os::raw::c_ulong,
    pub extRemote: ::std::os::raw::c_ulong,
    pub errFrame: ::std::os::raw::c_ulong,
    pub busLoad: ::std::os::raw::c_ulong,
    pub overruns: ::std::os::raw::c_ulong,
}

// ---- Manual extern declarations (supplement bindgen output) ----
// These ensure the key functions are always available even if bindgen
// has issues with certain preprocessor macros.

extern "C" {
    pub fn canInitializeLibrary();
    pub fn canGetVersion() -> ::std::os::raw::c_ushort;

    pub fn canGetErrorText(
        err: canStatus,
        buf: *mut ::std::os::raw::c_char,
        bufsiz: ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canGetNumberOfChannels(channelCount: *mut ::std::os::raw::c_int) -> canStatus;

    pub fn canGetChannelData(
        channel: ::std::os::raw::c_int,
        item: ::std::os::raw::c_int,
        buffer: *mut ::std::os::raw::c_void,
        bufsize: usize,
    ) -> canStatus;

    pub fn canOpenChannel(
        channel: ::std::os::raw::c_int,
        flags: ::std::os::raw::c_int,
    ) -> canHandle;

    pub fn canClose(hnd: canHandle) -> canStatus;
    pub fn canBusOn(hnd: canHandle) -> canStatus;
    pub fn canBusOff(hnd: canHandle) -> canStatus;
    pub fn canResetBus(hnd: canHandle) -> canStatus;

    pub fn canSetBusParams(
        hnd: canHandle,
        freq: ::std::os::raw::c_long,
        tseg1: ::std::os::raw::c_uint,
        tseg2: ::std::os::raw::c_uint,
        sjw: ::std::os::raw::c_uint,
        noSamp: ::std::os::raw::c_uint,
        syncmode: ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canGetBusParams(
        hnd: canHandle,
        freq: *mut ::std::os::raw::c_long,
        tseg1: *mut ::std::os::raw::c_uint,
        tseg2: *mut ::std::os::raw::c_uint,
        sjw: *mut ::std::os::raw::c_uint,
        noSamp: *mut ::std::os::raw::c_uint,
        syncmode: *mut ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canSetBitrate(
        hnd: canHandle,
        bitrate: ::std::os::raw::c_int,
    ) -> canStatus;

    pub fn canSetBusParamsFd(
        hnd: canHandle,
        freq_brs: ::std::os::raw::c_long,
        tseg1_brs: ::std::os::raw::c_uint,
        tseg2_brs: ::std::os::raw::c_uint,
        sjw_brs: ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canGetBusParamsFd(
        hnd: canHandle,
        freq_brs: *mut ::std::os::raw::c_long,
        tseg1_brs: *mut ::std::os::raw::c_uint,
        tseg2_brs: *mut ::std::os::raw::c_uint,
        sjw_brs: *mut ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canSetBusParamsTq(
        hnd: canHandle,
        nominal: kvBusParamsTq,
    ) -> canStatus;

    pub fn canGetBusParamsTq(
        hnd: canHandle,
        nominal: *mut kvBusParamsTq,
    ) -> canStatus;

    pub fn canSetBusParamsFdTq(
        hnd: canHandle,
        arbitration: kvBusParamsTq,
        data: kvBusParamsTq,
    ) -> canStatus;

    pub fn canGetBusParamsFdTq(
        hnd: canHandle,
        nominal: *mut kvBusParamsTq,
        data: *mut kvBusParamsTq,
    ) -> canStatus;

    pub fn canSetBusOutputControl(
        hnd: canHandle,
        drivertype: ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canGetBusOutputControl(
        hnd: canHandle,
        drivertype: *mut ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canWrite(
        hnd: canHandle,
        id: ::std::os::raw::c_long,
        msg: *mut ::std::os::raw::c_void,
        dlc: ::std::os::raw::c_uint,
        flag: ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canWriteWait(
        hnd: canHandle,
        id: ::std::os::raw::c_long,
        msg: *mut ::std::os::raw::c_void,
        dlc: ::std::os::raw::c_uint,
        flag: ::std::os::raw::c_uint,
        timeout: ::std::os::raw::c_ulong,
    ) -> canStatus;

    pub fn canWriteSync(
        hnd: canHandle,
        timeout: ::std::os::raw::c_ulong,
    ) -> canStatus;

    pub fn canRead(
        hnd: canHandle,
        id: *mut ::std::os::raw::c_long,
        msg: *mut ::std::os::raw::c_void,
        dlc: *mut ::std::os::raw::c_uint,
        flag: *mut ::std::os::raw::c_uint,
        time: *mut ::std::os::raw::c_ulong,
    ) -> canStatus;

    pub fn canReadWait(
        hnd: canHandle,
        id: *mut ::std::os::raw::c_long,
        msg: *mut ::std::os::raw::c_void,
        dlc: *mut ::std::os::raw::c_uint,
        flag: *mut ::std::os::raw::c_uint,
        time: *mut ::std::os::raw::c_ulong,
        timeout: ::std::os::raw::c_ulong,
    ) -> canStatus;

    pub fn canReadSync(
        hnd: canHandle,
        timeout: ::std::os::raw::c_ulong,
    ) -> canStatus;

    pub fn canReadSpecific(
        hnd: canHandle,
        id: ::std::os::raw::c_long,
        msg: *mut ::std::os::raw::c_void,
        dlc: *mut ::std::os::raw::c_uint,
        flag: *mut ::std::os::raw::c_uint,
        time: *mut ::std::os::raw::c_ulong,
    ) -> canStatus;

    pub fn canReadSpecificSkip(
        hnd: canHandle,
        id: ::std::os::raw::c_long,
        msg: *mut ::std::os::raw::c_void,
        dlc: *mut ::std::os::raw::c_uint,
        flag: *mut ::std::os::raw::c_uint,
        time: *mut ::std::os::raw::c_ulong,
    ) -> canStatus;

    pub fn canReadSyncSpecific(
        hnd: canHandle,
        id: ::std::os::raw::c_long,
        timeout: ::std::os::raw::c_ulong,
    ) -> canStatus;

    pub fn canAccept(
        hnd: canHandle,
        envelope: ::std::os::raw::c_long,
        flag: ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canSetAcceptanceFilter(
        hnd: canHandle,
        code: ::std::os::raw::c_uint,
        mask: ::std::os::raw::c_uint,
        is_extended: ::std::os::raw::c_int,
    ) -> canStatus;

    pub fn canReadStatus(
        hnd: canHandle,
        flags: *mut ::std::os::raw::c_ulong,
    ) -> canStatus;

    pub fn canReadErrorCounters(
        hnd: canHandle,
        txErr: *mut ::std::os::raw::c_uint,
        rxErr: *mut ::std::os::raw::c_uint,
        ovErr: *mut ::std::os::raw::c_uint,
    ) -> canStatus;

    pub fn canRequestChipStatus(hnd: canHandle) -> canStatus;

    pub fn canRequestBusStatistics(hnd: canHandle) -> canStatus;

    pub fn canGetBusStatistics(
        hnd: canHandle,
        stat: *mut canBusStatistics,
        bufsiz: usize,
    ) -> canStatus;

    pub fn canFlushReceiveQueue(hnd: canHandle) -> canStatus;
    pub fn canFlushTransmitQueue(hnd: canHandle) -> canStatus;
}
